const countries = [
  {
    countryCode: 'AED',
    currencyName: 'UAE Dirham',
    countryName: 'United Arab Emirates',
    currencySymbol: 'د.إ.‏',
  },
  {
    countryCode: 'AFN',
    currencyName: 'Afghan Afghani',
    countryName: 'Afghanistan',
    currencySymbol: '؋',
  },
  {
    countryCode: 'ALL',
    currencyName: 'Albanian Lek',
    countryName: 'Albania',
    currencySymbol: 'Lek',
  },
  {
    countryCode: 'AMD',
    currencyName: 'Armenian Dram',
    countryName: 'Armenia',
    currencySymbol: '֏',
  },
  {
    countryCode: 'ANG',
    currencyName: 'Netherlands Antillian Guilder',
    countryName: 'Netherlands Antilles',
    currencySymbol: 'ƒ',
  },
  {
    countryCode: 'AOA',
    currencyName: 'Angolan Kwanza',
    countryName: 'Angola',
    currencySymbol: 'Kz',
  },
  {
    countryCode: 'ARS',
    currencyName: 'Argentine Peso',
    countryName: 'Argentina',
    currencySymbol: '$',
  },
  {
    countryCode: 'AUD',
    currencyName: 'Australian Dollar',
    countryName: 'Australia',
    currencySymbol: '$',
  },
  {
    countryCode: 'AWG',
    currencyName: 'Aruban Florin',
    countryName: 'Aruba',
    currencySymbol: 'ƒ',
  },
  {
    countryCode: 'AZN',
    currencyName: 'Azerbaijani Manat',
    countryName: 'Azerbaijan',
    currencySymbol: '₼',
  },
  {
    countryCode: 'BAM',
    currencyName: 'Bosnia and Herzegovina Mark',
    countryName: 'Bosnia and Herzegovina',
    currencySymbol: 'КМ',
  },
  {
    countryCode: 'BBD',
    currencyName: 'Barbados Dollar',
    countryName: 'Barbados',
    currencySymbol: '$',
  },
  {
    countryCode: 'BDT',
    currencyName: 'Bangladeshi Taka',
    countryName: 'Bangladesh',
    currencySymbol: '৳',
  },
  {
    countryCode: 'BGN',
    currencyName: 'Bulgarian Lev',
    countryName: 'Bulgaria',
    currencySymbol: 'лв.',
  },
  {
    countryCode: 'BHD',
    currencyName: 'Bahraini Dinar',
    countryName: 'Bahrain',
    currencySymbol: 'د.ب.‏',
  },
  {
    countryCode: 'BIF',
    currencyName: 'Burundian Franc',
    countryName: 'Burundi',
    currencySymbol: 'FBu',
  },
  {
    countryCode: 'BMD',
    currencyName: 'Bermudian Dollar',
    countryName: 'Bermuda',
    currencySymbol: '$',
  },
  {
    countryCode: 'BND',
    currencyName: 'Brunei Dollar',
    countryName: 'Brunei',
    currencySymbol: '$',
  },
  {
    countryCode: 'BOB',
    currencyName: 'Bolivian Boliviano',
    countryName: 'Bolivia',
    currencySymbol: 'Bs',
  },
  {
    countryCode: 'BRL',
    currencyName: 'Brazilian Real',
    countryName: 'Brazil',
    currencySymbol: 'R$',
  },
  {
    countryCode: 'BSD',
    currencyName: 'Bahamian Dollar',
    countryName: 'Bahamas',
    currencySymbol: '$',
  },
  {
    countryCode: 'BTN',
    currencyName: 'Bhutanese Ngultrum',
    countryName: 'Bhutan',
    currencySymbol: 'Nu.',
  },
  {
    countryCode: 'BWP',
    currencyName: 'Botswana Pula',
    countryName: 'Botswana',
    currencySymbol: 'P',
  },
  {
    countryCode: 'BYN',
    currencyName: 'Belarusian Ruble',
    countryName: 'Belarus',
    currencySymbol: 'р.',
  },
  {
    countryCode: 'BZD',
    currencyName: 'Belize Dollar',
    countryName: 'Belize',
    currencySymbol: 'BZ$',
  },
  {
    countryCode: 'CAD',
    currencyName: 'Canadian Dollar',
    countryName: 'Canada',
    currencySymbol: '$',
  },
  {
    countryCode: 'CDF',
    currencyName: 'Congolese Franc',
    countryName: 'Democratic Republic of the Congo',
    currencySymbol: 'FC',
  },
  {
    countryCode: 'CHF',
    currencyName: 'Swiss Franc',
    countryName: 'Switzerland',
    currencySymbol: 'CHF',
  },
  {
    countryCode: 'CLP',
    currencyName: 'Chilean Peso',
    countryName: 'Chile',
    currencySymbol: '$',
  },
  {
    countryCode: 'CNY',
    currencyName: 'Chinese Renminbi',
    countryName: 'China',
    currencySymbol: '¥',
  },
  {
    countryCode: 'COP',
    currencyName: 'Colombian Peso',
    countryName: 'Colombia',
    currencySymbol: '$',
  },
  {
    countryCode: 'CRC',
    currencyName: 'Costa Rican Colon',
    countryName: 'Costa Rica',
    currencySymbol: '₡',
  },
  {
    countryCode: 'CUC',
    currencyName: 'Cuban Convertible Peso',
    countryName: 'Cuba CUC',
    currencySymbol: 'CUC',
  },
  {
    countryCode: 'CUP',
    currencyName: 'Cuban Peso',
    countryName: 'Cuba CUP',
    currencySymbol: '$MN',
  },
  {
    countryCode: 'CVE',
    currencyName: 'Cape Verdean Escudo',
    countryName: 'Cape Verde',
    currencySymbol: '$',
  },
  {
    countryCode: 'CZK',
    currencyName: 'Czech Koruna',
    countryName: 'Czech Republic',
    currencySymbol: 'Kč',
  },
  {
    countryCode: 'DJF',
    currencyName: 'Djiboutian Franc',
    countryName: 'Djibouti',
    currencySymbol: 'Fdj',
  },
  {
    countryCode: 'DKK',
    currencyName: 'Danish Krone',
    countryName: 'Denmark',
    currencySymbol: 'kr.',
  },
  {
    countryCode: 'DOP',
    currencyName: 'Dominican Peso',
    countryName: 'Dominican Republic',
    currencySymbol: 'RD$',
  },
  {
    countryCode: 'DZD',
    currencyName: 'Algerian Dinar',
    countryName: 'Algeria',
    currencySymbol: 'د.ج.‏',
  },
  {
    countryCode: 'EGP',
    currencyName: 'Egyptian Pound',
    countryName: 'Egypt',
    currencySymbol: 'ج.م.‏',
  },
  {
    countryCode: 'ERN',
    currencyName: 'Eritrean Nakfa',
    countryName: 'Eritrea',
    currencySymbol: 'Nfk',
  },
  {
    countryCode: 'ETB',
    currencyName: 'Ethiopian Birr',
    countryName: 'Ethiopia',
    currencySymbol: 'ETB',
  },
  {
    countryCode: 'EUR',
    currencyName: 'Euro',
    countryName: 'European Union',
    currencySymbol: '€',
  },
  {
    countryCode: 'FJD',
    currencyName: 'Fiji Dollar',
    countryName: 'Fiji',
    currencySymbol: '$',
  },
  {
    countryCode: 'FKP',
    currencyName: 'Falkland Islands Pound',
    countryName: 'Falkland Islands',
    currencySymbol: '£',
  },
  {
    countryCode: 'FOK',
    currencyName: 'Faroese Króna',
    countryName: 'Faroe Islands',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'GBP',
    currencyName: 'Pound Sterling',
    countryName: 'United Kingdom',
    currencySymbol: '£',
  },
  {
    countryCode: 'GEL',
    currencyName: 'Georgian Lari',
    countryName: 'Georgia',
    currencySymbol: 'GEL',
  },
  {
    countryCode: 'GGP',
    currencyName: 'Guernsey Pound',
    countryName: 'Guernsey',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'GHS',
    currencyName: 'Ghanaian Cedi',
    countryName: 'Ghana',
    currencySymbol: '₵',
  },
  {
    countryCode: 'GIP',
    currencyName: 'Gibraltar Pound',
    countryName: 'Gibraltar',
    currencySymbol: '£',
  },
  {
    countryCode: 'GMD',
    currencyName: 'Gambian Dalasi',
    countryName: 'The Gambia',
    currencySymbol: 'D',
  },
  {
    countryCode: 'GNF',
    currencyName: 'Guinean Franc',
    countryName: 'Guinea',
    currencySymbol: 'FG',
  },
  {
    countryCode: 'GTQ',
    currencyName: 'Guatemalan Quetzal',
    countryName: 'Guatemala',
    currencySymbol: 'Q',
  },
  {
    countryCode: 'GYD',
    currencyName: 'Guyanese Dollar',
    countryName: 'Guyana',
    currencySymbol: '$',
  },
  {
    countryCode: 'HKD',
    currencyName: 'Hong Kong Dollar',
    countryName: 'Hong Kong',
    currencySymbol: 'HK$',
  },
  {
    countryCode: 'HNL',
    currencyName: 'Honduran Lempira',
    countryName: 'Honduras',
    currencySymbol: 'L.',
  },
  {
    countryCode: 'HRK',
    currencyName: 'Croatian Kuna',
    countryName: 'Croatia',
    currencySymbol: 'kn',
  },
  {
    countryCode: 'HTG',
    currencyName: 'Haitian Gourde',
    countryName: 'Haiti',
    currencySymbol: 'G',
  },
  {
    countryCode: 'HUF',
    currencyName: 'Hungarian Forint',
    countryName: 'Hungary',
    currencySymbol: 'Ft',
  },
  {
    countryCode: 'IDR',
    currencyName: 'Indonesian Rupiah',
    countryName: 'Indonesia',
    currencySymbol: 'Rp',
  },
  {
    countryCode: 'ILS',
    currencyName: 'Israeli New Shekel',
    countryName: 'Israel',
    currencySymbol: '₪',
  },
  {
    countryCode: 'IMP',
    currencyName: 'Manx Pound',
    countryName: 'Isle of Man',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'INR',
    currencyName: 'Indian Rupee',
    countryName: 'India',
    currencySymbol: '₹',
  },
  {
    countryCode: 'IQD',
    currencyName: 'Iraqi Dinar',
    countryName: 'Iraq',
    currencySymbol: 'د.ع.‏',
  },
  {
    countryCode: 'IRR',
    currencyName: 'Iranian Rial',
    countryName: 'Iran',
    currencySymbol: '﷼',
  },
  {
    countryCode: 'ISK',
    currencyName: 'Icelandic Króna',
    countryName: 'Iceland',
    currencySymbol: 'kr.',
  },
  {
    countryCode: 'JMD',
    currencyName: 'Jamaican Dollar',
    countryName: 'Jamaica',
    currencySymbol: 'J$',
  },
  {
    countryCode: 'JOD',
    currencyName: 'Jordanian Dinar',
    countryName: 'Jordan',
    currencySymbol: 'د.ا.‏',
  },
  {
    countryCode: 'JPY',
    currencyName: 'Japanese Yen',
    countryName: 'Japan',
    currencySymbol: '¥',
  },
  {
    countryCode: 'KES',
    currencyName: 'Kenyan Shilling',
    countryName: 'Kenya',
    currencySymbol: 'KSh',
  },
  {
    countryCode: 'KGS',
    currencyName: 'Kyrgyzstani Som',
    countryName: 'Kyrgyzstan',
    currencySymbol: 'сом',
  },
  {
    countryCode: 'KHR',
    currencyName: 'Cambodian Riel',
    countryName: 'Cambodia',
    currencySymbol: '៛',
  },
  {
    countryCode: 'KID',
    currencyName: 'Kiribati Dollar',
    countryName: 'Kiribati',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'KMF',
    currencyName: 'Comorian Franc',
    countryName: 'Comoros',
    currencySymbol: 'CF',
  },
  {
    countryCode: 'KRW',
    currencyName: 'South Korean Won',
    countryName: 'South Korea',
    currencySymbol: '₩',
  },
  {
    countryCode: 'KWD',
    currencyName: 'Kuwaiti Dinar',
    countryName: 'Kuwait',
    currencySymbol: 'د.ك.‏',
  },
  {
    countryCode: 'KYD',
    currencyName: 'Cayman Islands Dollar',
    countryName: 'Cayman Islands',
    currencySymbol: '$',
  },
  {
    countryCode: 'KZT',
    currencyName: 'Kazakhstani Tenge',
    countryName: 'Kazakhstan',
    currencySymbol: '₸',
  },
  {
    countryCode: 'LAK',
    currencyName: 'Lao Kip',
    countryName: 'Laos',
    currencySymbol: '₭',
  },
  {
    countryCode: 'LBP',
    currencyName: 'Lebanese Pound',
    countryName: 'Lebanon',
    currencySymbol: 'ل.ل.‏',
  },
  {
    countryCode: 'LKR',
    currencyName: 'Sri Lanka Rupee',
    countryName: 'Sri Lanka',
    currencySymbol: '₨',
  },
  {
    countryCode: 'LRD',
    currencyName: 'Liberian Dollar',
    countryName: 'Liberia',
    currencySymbol: '$',
  },
  {
    countryCode: 'LSL',
    currencyName: 'Lesotho Loti',
    countryName: 'Lesotho',
    currencySymbol: 'M',
  },
  {
    countryCode: 'LYD',
    currencyName: 'Libyan Dinar',
    countryName: 'Libya',
    currencySymbol: 'د.ل.‏',
  },
  {
    countryCode: 'MAD',
    currencyName: 'Moroccan Dirham',
    countryName: 'Morocco',
    currencySymbol: 'د.م.‏',
  },
  {
    countryCode: 'MDL',
    currencyName: 'Moldovan Leu',
    countryName: 'Moldova',
    currencySymbol: 'lei',
  },
  {
    countryCode: 'MGA',
    currencyName: 'Malagasy Ariary',
    countryName: 'Madagascar',
    currencySymbol: 'Ar',
  },
  {
    countryCode: 'MKD',
    currencyName: 'Macedonian Denar',
    countryName: 'North Macedonia',
    currencySymbol: 'ден.',
  },
  {
    countryCode: 'MMK',
    currencyName: 'Burmese Kyat',
    countryName: 'Myanmar',
    currencySymbol: 'K',
  },
  {
    countryCode: 'MNT',
    currencyName: 'Mongolian Tögrög',
    countryName: 'Mongolia',
    currencySymbol: '₮',
  },
  {
    countryCode: 'MOP',
    currencyName: 'Macanese Pataca',
    countryName: 'Macau',
    currencySymbol: 'MOP$',
  },
  {
    countryCode: 'MRU',
    currencyName: 'Mauritanian Ouguiya',
    countryName: 'Mauritania',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'MUR',
    currencyName: 'Mauritian Rupee',
    countryName: 'Mauritius',
    currencySymbol: '₨',
  },
  {
    countryCode: 'MVR',
    currencyName: 'Maldivian Rufiyaa',
    countryName: 'Maldives',
    currencySymbol: 'MVR',
  },
  {
    countryCode: 'MWK',
    currencyName: 'Malawian Kwacha',
    countryName: 'Malawi',
    currencySymbol: 'MK',
  },
  {
    countryCode: 'MXN',
    currencyName: 'Mexican Peso',
    countryName: 'Mexico',
    currencySymbol: '$',
  },
  {
    countryCode: 'MYR',
    currencyName: 'Malaysian Ringgit',
    countryName: 'Malaysia',
    currencySymbol: 'RM',
  },
  {
    countryCode: 'MZN',
    currencyName: 'Mozambican Metical',
    countryName: 'Mozambique',
    currencySymbol: 'MT',
  },
  {
    countryCode: 'NAD',
    currencyName: 'Namibian Dollar',
    countryName: 'Namibia',
    currencySymbol: '$',
  },
  {
    countryCode: 'NGN',
    currencyName: 'Nigerian Naira',
    countryName: 'Nigeria',
    currencySymbol: '₦',
  },
  {
    countryCode: 'NIO',
    currencyName: 'Nicaraguan Córdoba',
    countryName: 'Nicaragua',
    currencySymbol: 'C$',
  },
  {
    countryCode: 'NOK',
    currencyName: 'Norwegian Krone',
    countryName: 'Norway',
    currencySymbol: 'kr',
  },
  {
    countryCode: 'NPR',
    currencyName: 'Nepalese Rupee',
    countryName: 'Nepal',
    currencySymbol: '₨',
  },
  {
    countryCode: 'NZD',
    currencyName: 'New Zealand Dollar',
    countryName: 'New Zealand',
    currencySymbol: '$',
  },
  {
    countryCode: 'OMR',
    currencyName: 'Omani Rial',
    countryName: 'Oman',
    currencySymbol: '﷼',
  },
  {
    countryCode: 'PAB',
    currencyName: 'Panamanian Balboa',
    countryName: 'Panama',
    currencySymbol: 'B/.',
  },
  {
    countryCode: 'PEN',
    currencyName: 'Peruvian Sol',
    countryName: 'Peru',
    currencySymbol: 'S/.',
  },
  {
    countryCode: 'PGK',
    currencyName: 'Papua New Guinean Kina',
    countryName: 'Papua New Guinea',
    currencySymbol: 'K',
  },
  {
    countryCode: 'PHP',
    currencyName: 'Philippine Peso',
    countryName: 'Philippines',
    currencySymbol: '₱',
  },
  {
    countryCode: 'PKR',
    currencyName: 'Pakistani Rupee',
    countryName: 'Pakistan',
    currencySymbol: '₨',
  },
  {
    countryCode: 'PLN',
    currencyName: 'Polish Złoty',
    countryName: 'Poland',
    currencySymbol: 'zł',
  },
  {
    countryCode: 'PYG',
    currencyName: 'Paraguayan Guaraní',
    countryName: 'Paraguay',
    currencySymbol: '₲',
  },
  {
    countryCode: 'QAR',
    currencyName: 'Qatari Riyal',
    countryName: 'Qatar',
    currencySymbol: '﷼',
  },
  {
    countryCode: 'RON',
    currencyName: 'Romanian Leu',
    countryName: 'Romania',
    currencySymbol: 'L',
  },
  {
    countryCode: 'RSD',
    currencyName: 'Serbian Dinar',
    countryName: 'Serbia',
    currencySymbol: 'Дин.',
  },
  {
    countryCode: 'RUB',
    currencyName: 'Russian Ruble',
    countryName: 'Russia',
    currencySymbol: '₽',
  },
  {
    countryCode: 'RWF',
    currencyName: 'Rwandan Franc',
    countryName: 'Rwanda',
    currencySymbol: 'RWF',
  },
  {
    countryCode: 'SAR',
    currencyName: 'Saudi Riyal',
    countryName: 'Saudi Arabia',
    currencySymbol: '﷼',
  },
  {
    countryCode: 'SBD',
    currencyName: 'Solomon Islands Dollar',
    countryName: 'Solomon Islands',
    currencySymbol: '$',
  },
  {
    countryCode: 'SCR',
    currencyName: 'Seychellois Rupee',
    countryName: 'Seychelles',
    currencySymbol: '₨',
  },
  {
    countryCode: 'SDG',
    currencyName: 'Sudanese Pound',
    countryName: 'Sudan',
    currencySymbol: '£‏',
  },
  {
    countryCode: 'SEK',
    currencyName: 'Swedish Krona',
    countryName: 'Sweden',
    currencySymbol: 'kr',
  },
  {
    countryCode: 'SGD',
    currencyName: 'Singapore Dollar',
    countryName: 'Singapore',
    currencySymbol: '$',
  },
  {
    countryCode: 'SHP',
    currencyName: 'Saint Helena Pound',
    countryName: 'Saint Helena',
    currencySymbol: '£',
  },
  {
    countryCode: 'SLL',
    currencyName: 'Sierra Leonean Leone',
    countryName: 'Sierra Leone',
    currencySymbol: 'Le',
  },
  {
    countryCode: 'SOS',
    currencyName: 'Somali Shilling',
    countryName: 'Somalia',
    currencySymbol: 'S',
  },
  {
    countryCode: 'SRD',
    currencyName: 'Surinamese Dollar',
    countryName: 'Suriname',
    currencySymbol: '$',
  },
  {
    countryCode: 'SSP',
    currencyName: 'South Sudanese Pound',
    countryName: 'South Sudan',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'STN',
    currencyName: 'São Tomé and Príncipe Dobra',
    countryName: 'São Tomé and Príncipe',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'SYP',
    currencyName: 'Syrian Pound',
    countryName: 'Syria',
    currencySymbol: '£',
  },
  {
    countryCode: 'SZL',
    currencyName: 'Eswatini Lilangeni',
    countryName: 'Eswatini',
    currencySymbol: 'E',
  },
  {
    countryCode: 'THB',
    currencyName: 'Thai Baht',
    countryName: 'Thailand',
    currencySymbol: '฿',
  },
  {
    countryCode: 'TJS',
    currencyName: 'Tajikistani Somoni',
    countryName: 'Tajikistan',
    currencySymbol: 'TJS',
  },
  {
    countryCode: 'TMT',
    currencyName: 'Turkmenistan Manat',
    countryName: 'Turkmenistan',
    currencySymbol: 'm',
  },
  {
    countryCode: 'TND',
    currencyName: 'Tunisian Dinar',
    countryName: 'Tunisia',
    currencySymbol: 'د.ت.‏',
  },
  {
    countryCode: 'TOP',
    currencyName: 'Tongan Paʻanga',
    countryName: 'Tonga',
    currencySymbol: 'T$',
  },
  {
    countryCode: 'TRY',
    currencyName: 'Turkish Lira',
    countryName: 'Turkey',
    currencySymbol: '₺',
  },
  {
    countryCode: 'TTD',
    currencyName: 'Trinidad and Tobago Dollar',
    countryName: 'Trinidad and Tobago',
    currencySymbol: 'TT$',
  },
  {
    countryCode: 'TVD',
    currencyName: 'Tuvaluan Dollar',
    countryName: 'Tuvalu',
    currencySymbol: '$',
  },
  {
    countryCode: 'TWD',
    currencyName: 'New Taiwan Dollar',
    countryName: 'Taiwan',
    currencySymbol: 'NT$',
  },
  {
    countryCode: 'TZS',
    currencyName: 'Tanzanian Shilling',
    countryName: 'Tanzania',
    currencySymbol: 'TSh',
  },
  {
    countryCode: 'UAH',
    currencyName: 'Ukrainian Hryvnia',
    countryName: 'Ukraine',
    currencySymbol: '₴',
  },
  {
    countryCode: 'UGX',
    currencyName: 'Ugandan Shilling',
    countryName: 'Uganda',
    currencySymbol: 'USh',
  },
  {
    countryCode: 'USD',
    currencyName: 'United States Dollar',
    countryName: 'United States',
    currencySymbol: '$',
  },
  {
    countryCode: 'UYU',
    currencyName: 'Uruguayan Peso',
    countryName: 'Uruguay',
    currencySymbol: '$U',
  },
  {
    countryCode: 'UZS',
    currencyName: "Uzbekistani So'm",
    countryName: 'Uzbekistan',
    currencySymbol: 'сўм',
  },
  {
    countryCode: 'VES',
    currencyName: 'Venezuelan Bolívar Soberano',
    countryName: 'Venezuela',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'VND',
    currencyName: 'Vietnamese Đồng',
    countryName: 'Vietnam',
    currencySymbol: '₫',
  },
  {
    countryCode: 'VUV',
    currencyName: 'Vanuatu Vatu',
    countryName: 'Vanuatu',
    currencySymbol: 'VT',
  },
  {
    countryCode: 'WST',
    currencyName: 'Samoan Tālā',
    countryName: 'Samoa',
    currencySymbol: 'WS$',
  },
  {
    countryCode: 'XAF',
    currencyName: 'Central African CFA Franc',
    countryName: 'CEMAC',
    currencySymbol: 'F',
  },
  {
    countryCode: 'XCD',
    currencyName: 'East Caribbean Dollar',
    countryName: 'Organisation of Eastern Caribbean States',
    currencySymbol: '$',
  },
  {
    countryCode: 'XDR',
    currencyName: 'Special Drawing Rights',
    countryName: 'International Monetary Fund',
    currencySymbol: 'undefined',
  },
  {
    countryCode: 'XOF',
    currencyName: 'West African CFA franc',
    countryName: 'CFA',
    currencySymbol: 'F',
  },
  {
    countryCode: 'XPF',
    currencyName: 'CFP Franc',
    countryName: "Collectivités d'Outre-Mer",
    currencySymbol: 'F',
  },
  {
    countryCode: 'YER',
    currencyName: 'Yemeni Rial',
    countryName: 'Yemen',
    currencySymbol: '﷼',
  },
  {
    countryCode: 'ZAR',
    currencyName: 'South African Rand',
    countryName: 'South Africa',
    currencySymbol: 'R',
  },
  {
    countryCode: 'ZMW',
    currencyName: 'Zambian Kwacha',
    countryName: 'Zambia',
    currencySymbol: 'ZK',
  },
]

export default countries
